#define WINDOW_WIDTH 800
#define WINDOW_HEIGHT 600
#define WINDOW_LABEL "DOOM CLONE"

#define PLAYER_STARTING_POSITION (Vector2){0.0f, 0.0f}
#define PLAYER_SIZE 30
#define PLAYER_SPEED 200.0f
#define PLAYER_COLOR GREEN

#define BACKGROUND_COLOR BLACK