#pragma once

#define WINDOW_WIDTH 1280
#define WINDOW_HEIGHT 720
#define WINDOW_LABEL "DOOM CLONE"

#define GRID_SIZE 32

#define PLAYER_STARTING_POSITION (Vector2){48.0f, 48.0f}
#define PLAYER_SIZE GRID_SIZE / 2
#define PLAYER_SPEED 200.0f
#define PLAYER_TURN_SPEED 30.0f
#define PLAYER_COLOR GREEN

#define LEVEL_GRID_COlOR GRAY
#define LEVEL_GRID_SIZE GRID_SIZE

#define BACKGROUND_COLOR BLACK