#pragma once

#define WINDOW_WIDTH 800
#define WINDOW_HEIGHT 600
#define WINDOW_LABEL "DOOM CLONE"

#define GRID_SIZE 16

#define PLAYER_STARTING_POSITION (Vector2){48.0f, 48.0f}
#define PLAYER_SIZE GRID_SIZE
#define PLAYER_SPEED 200.0f
#define PLAYER_COLOR GREEN

#define LEVEL_GRID_COlOR GRAY
#define LEVEL_GRID_SIZE GRID_SIZE

#define BACKGROUND_COLOR BLACK